name: CI-CD

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build_an_push_react_app_to_Docker_Hub:
    name: "[PROD] Build and push react app docker image"
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 #v3.6.0

      - name: set up QEMU
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 #v2.2.0

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 #v2.10.0

      - name: login to DockerHub
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc #v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 #v4.1.1
        with:
          context: ./
          file: ./react-app/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_ORG }}/balancy-ts-demo:main

  build_an_push_dashboard_app_to_Docker_Hub:
    name: "[PROD] Build and push dashboard app docker image"
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 #v3.6.0

      - name: set up QEMU
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 #v2.2.0

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 #v2.10.0

      - name: login to DockerHub
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc #v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 #v4.1.1
        with:
          context: ./
          file: ./dashboard-app/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_ORG }}/balancy-ts-dashboard-demo:main
